CREATE TABLE account
(
    id        VARCHAR(255) NOT NULL,
    title     VARCHAR(255),
    amount    DECIMAL,
    budget_id BIGINT,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE budget
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slug  VARCHAR(255),
    month INTEGER,
    year  INTEGER,
    CONSTRAINT pk_budget PRIMARY KEY (id)
);

CREATE TABLE expense
(
    id                  VARCHAR(255) NOT NULL,
    title               VARCHAR(255),
    amount              DECIMAL,
    date                TIMESTAMP WITHOUT TIME ZONE,
    expense_type_id     BIGINT,
    expense_category_id BIGINT,
    budget_id           BIGINT,
    CONSTRAINT pk_expense PRIMARY KEY (id)
);

CREATE TABLE expense_category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_expensecategory PRIMARY KEY (id)
);

CREATE TABLE expense_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_expensetype PRIMARY KEY (id)
);

CREATE TABLE income
(
    id        VARCHAR(255) NOT NULL,
    title     VARCHAR(255),
    amount    DECIMAL,
    date      TIMESTAMP WITHOUT TIME ZONE,
    budget_id BIGINT,
    CONSTRAINT pk_income PRIMARY KEY (id)
);

ALTER TABLE expense_category
    ADD CONSTRAINT uc_expensecategory_name UNIQUE (name);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_BUDGET FOREIGN KEY (budget_id) REFERENCES budget (id);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_BUDGET FOREIGN KEY (budget_id) REFERENCES budget (id);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_EXPENSECATEGORY FOREIGN KEY (expense_category_id) REFERENCES expense_category (id);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_EXPENSETYPE FOREIGN KEY (expense_type_id) REFERENCES expense_type (id);

ALTER TABLE income
    ADD CONSTRAINT FK_INCOME_ON_BUDGET FOREIGN KEY (budget_id) REFERENCES budget (id);